

longstring = """\ 

MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMyssddhhNNhNmmMMMMNmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdNmooh//...--------------:.-:ohhhhhhhmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhoo---------------:::::::::::::::----://///o+shhmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh+-..----------------------::::::::::/::::///++/////:/osmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd+:-----------------------------------::////://////+//////:::soyhmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdy:----:------------------------::----::--:::://////////++////::::--:+oyhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+---::::::::::----------------:::::::::::::::::::::/:////+///::::::::::::::/shNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy+:-::::::::::::::-------------------:::::::::::::::::::::////:::::::::::///::::::/hNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmo:-::::::::///:::-----..--------------:::::::://///::::::--:::::-----::::::////:::/::::sNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMmo:-::::::://///::-----....--.---------::::::::::://///////:::::-:--------:::///////////::::dMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMNh/:-::::::://///:::-------.........----:::::::::::::////////////////::-------::::://///////::::hMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMh/--::::::://////:::::::-----.......-----::::-::::://////////::/:////////::::--:::::://///////:::-yMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNs--:::///////////:::/:::::----....------------::////++/////+//////::/++++////::::--::://////////::--sMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMd/-:://///////////://////::::-----------------:/++oooooooooooo++++++////+++++////:::----:::////////::--+mMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNh:://////////////////////::::::::::---------:/+ooooosssooooooooo+++++++/++++++///:::::---:::://////::::--+MMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMd+:://///////////////////:::::://:::::-----::/++++++++++++++///+++++++++++++++++///::::::::--::://///::::::-yMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMN/://///////////////+////////////::::::::::////////:::::///::::::://///+++++++++++////::::::::::::::///:::::--yMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMm/:/++/////////////////////////////:::::::////:::-----------------:::::://////++++++++++/:::::::::::::///:::::-:hMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMM+-////////////////::////:////////:::::::::::------.......---....--------::::://///+++ooo++/:::::::::::::/::::----NMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMm-::////++///////:://:::::::::::::::::::------.....................----------:::::///+oooooo//::::://///////::---.oMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMm::::///++//////////:::::::::::::::----............................---------------::://++oooso+/::::///////////:::-.sMMMMMMMMMMMMM
MMMMMMMMMMMMMMd-::////+++//////////:::---::------........................-........----.------------::://+ossso+/:::////////+///:::-.oNMMMMMMMMMMM
MMMMMMMMMMMMMN:::://+//++//////:::---------.............................................------------:::://osyyo+/::////////+++///:::-/NMMMMMMMMMM
MMMMMMMMMMMMN::::/++////////::::-----....................................................------------::://+osyyo+///////////++////::--sMMMMMMMMMM
MMMMMMMMMMMN/::////////////::::-------......................................................--------:---://+oyyyo////////////+++///::--+NMMMMMMMM
MMMMMMMMMMm-://////////+//::::-------....................`....................................-----:::--:://+oyys+/::////++///++++////:--hMMMMMMM
MMMMMMMMMN/:////////+++////::-------........................................................-------:::--::://+ssoo//:///+++/////+++/////--sMMMMMM
MMMMMMMMM/:///:///+++++///::-------...........................`............................-------:::--::::://+ss++/:////+++//+//++++:::::-yMMMMM
MMMMMMMMy://://++++++++//:::-------...........................``...........................-------------::::://ooo+///////++//++/++++//:----yMMMM
MMMMMMMm:/://+++++++++////::-------........................................................------------:::::::/+++///://///++/++++++++//:----hMMM
MMMMMMN/://+++++ooo++////::---------...................................................-.-------------:::::::://++///////////+/+o+/+++///:---/MMM
MMMMMh/://+++oooooo+++//::::-------................`.....................................---------------::::::/+++///////////+//+++/+///:::--.NMM
MMMm/:://+++oooooo++++/:::::------..-..............`........................................----------------:://o+////++++/////+++///+///::::-NMM
MMM+:///++++oooooooo+///:::-------------------........``......`..`.......................-...---------:::---://+++///+++++//////+///////:/::::+MM
MMo:/+++oooooooooo++///::::---------::::/::::::::::--...````............`...................------------:---:/+++////++o+++/////+++/:///::/:::-sM
MN./++o+++ooooooo+++///::::----:::------:--:-:::::::::::-....................................--------:-----:/++++////+oos++/////+o++/:///::::::+M
MN-++oooooooo+++++++//::::-----------::/++o++++++/::-:::/:--..................................-------::---:/++++///:++oooso+//::/++++/:/::::::-.M
MN-/+ooooo+oooo++++/:::::-----------/+syhddhhhyssoo++//:::::---...-.....................-......-------::::/+++++///:++ooosso+/::/+++//:::/:::--.M
MM+:+++oo+ooo+++++/::::::-----.--:+oyhdhyshyysyyso+///////:::----.......--......--:::::::::------------:://+oo+//:/:/oooossso+/::/++//::://::--/M
MMN:/ooooo++++++//::://:--------::/++oo+:/o++/o+oo+/:--::::::--.......---------:///++//:::/:::::::::----:/+oo+++/////+oosssso+//://////:::/::--oM
MMMd:+ooooo++++//////+/:-----.------:::://+++++++/://-----:::--......-:::::///+++o++//:::::-::::://:::-::/+ooo++/////+osssssso+/:://////:/:--:-oM
MMMN//ooo++++++//+/++/::----....-----------::::::::://:-..-:---.....--:/+++ooo+++++oooooooo+/::::::://:::/+oo+++/////+ossssssso+/::////////----hM
MMMh-+oo+++++ooo+++//:::-----..--------........---------..----......-:/++oo/::::--:+ossyddddhyo//::::///:/+o+++++////+ossyyysooo+:::://////:--sMM
MMMh-+oooo++ossso++/::---------....--------.--------......---.......-:++++/---::///+ss++yyhdmmddy+/::////+++++++++/++/+osyyyysoo+/:::::///::-oMMM
MMMM+/ssso+/osyyy+/::--::------................------..-.----.......-:+//::::////:::o+/osossshmmmho///////+++++++++++++ooosssssoo+/://:://::+NMMM
MMMMs:osso///oyyo/:------------.....................--.-----.......--/+//:--------::://+ooo++oyhddyo//////+++++++//+++++oooooosso+/:::///:/dMMMMM
MMMMM++sso:--+sy+:-----:--------......................-----.......--:/+/::-:-------.----:://+oooo+o+///////++oo++//+++++o+oo++oooo+::://::NMMMMMM
MMMMMm++oo:..-os:------::------......................------......---:///:::::--------------::::::::::://////+oooo+//++++oo++/+/+o++/:::/:yMMMMMMM
MMMMMMN+/+/-`.::..-----::-------......................--.--......--:://:/:-----.....-------:::::::---::::://+oooo+////+++o++////++++//::-dMMMMMMM
MMMMMMMN/:/:.`.-..-----::-------....................-.--.-......-::::/://:--.-----.....-------------:-::::/+ossooo+////++o++++//+++++//-sMMMMMMMM
MMMMMMMMNo:/:.`.----.--::-------.................--------......--::::://::--............-....------:-::::::/oosooo++/////++/+oo+///++/:oNMMMMMMMM
MMMMMMMMMMh:/-``------::::------..---...--..--------..---......--:::://:::--...............-----::::::::://+osssoso++////////+oss+///:oMMMMMMMMMM
MMMMMMMMMMMm::-`.--:::::::----------------::::::---...---.......--:/++//:---..............-----::::::::///+oossssso++////////+oss+//:+MMMMMMMMMMM
MMMMMMMMMMMMMy:-.-/oo/:::::::--------:::://:---.---...---.......--::+/://:---.............----:::::::::///+ooossyooo+////////++o+//:sMMMMMMMMMMMM
MMMMMMMMMMMMMMMy+`.:+/::::::::::::::::///:---------------.......---:+::///::----........-----::::::::////++++osssooo++//+////++////hMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMmsh:::::::::::::::////:-----------:/:----.....--::/+///+/::::-------------::::::::////++++++ssssoooo+++++++///:/smMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMN+-:---::::::////:--------.....--::::------:://+o++++:---:::-----------:::::://////+++////+oossso++oo+++//+yMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMm--------::::/:::--------......--::::::///+osyyso+//:-----::::-----::::::::://////++++/:///+oooo++ooo++:sMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMM/----------::--:--------........--://++oooooo+//::::------:::::::::::::://////////////:::/+++++++ooo+:oMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMM/---------------:///:::---.......--::::////////:::::::--:-::::::::::::////////+//+/////:::::-:+ooso+:oMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMd---.-----..--..-oddds++//:::-----------:::-::::::::::::::::::::::::://////////++++////:----/+oooo/:yMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMM+.--.----...--..-+hh/-:://:///////:/::::::::::::::::::-:::::::::::////////////+o++////:-::+oooo+:omMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMN---.----...--..--/+/:-.-.`.---::+////+++++++++++//:::::::::::::://///////////+o++//::/+++oo+/+smMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMM+.-..---..-------:://:-.```````.-.`.-:--:+//syhhhhyo+:::::::--:::///////////+o+//+++++////oydNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMd.--.-.------------:/:::-...```..``..-..-..-shhmmdho:---------::://:://////////++sssssshmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMM---.--.-------------::::::------..--:-:/:-/ysso+/:--------.--:::/:::////::/+dNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMM+.-..-..-------------------:---:::////++++++///::::----..---::/::::///:-+dNMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMd.--.-..---.--------------------::::/:////+/////::::--..--:://:-:::/::+dMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMM+.-.--.------------------------------::://///:::::-----:://:--:://:-sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMN+...------------------------------:::::::/::::::::--:://:---:://::dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMNs..-----------------------------::::::::::::::::::://:----::/:-omMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMy..------------------...---------:::::::::::::/::/:-----:::-/hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh---:------...-.........-.----:-::-:::::::::///:---:--::::sNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm/--:------.............-----:-:-:::::::::///:-----::::smMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy:-::------...........-------::::::::::///:-::-:::/ymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy:-:::------------------::-:::::::::///::::--/smMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy+--:::::--------:-:::::::::::://///::://ydMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNho/--::::::::::::::::::::////////oydNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhy+/-:::::::::://:////:-:/sNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNhhsso//////ssyshhNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

"""

